services:
  - type: web
    name: autoluxe-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/cars
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 